server:
  port: 8080
spring:
  application:
    name: demo-redis
  redis:
    host: localhost
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        # 最大连接池数
        max-active: 8
        # 最小空闲连接
        min-idle: 0
        # 最大空闲连接
        max-idle: 8